vim.keymap.set( "n", "<leader>ga", function()
   vim.cmd("!git add .")
end )
vim.keymap.set( "n", "<leader>gc", function()
   vim.cmd("Git commit")
end )
vim.keymap.set( "n", "<leader>gp", function()
   vim.cmd("Git push")
end )
vim.keymap.set( "n", "<leader>fb", function()
   vim.cmd("Telescope git_branches")
end )
vim.keymap.set( "n", "<leader>fgf", function()
   vim.cmd("Telescope git_files")
end )
vim.keymap.set( "n", "<leader>fc", function()
   vim.cmd("Telescope git_files")
end )
